name: enough_mail
description: "enough_mail - IMAP, POP3, SMTP email library with high/low-level APIs and MIME parsing"
version: 2.2.3
repository: https://github.com/Enough-Software/enough_mail
topics:
  - email
  - imap
  - pop3
  - smtp
  - mime


environment:
  sdk: '>=3.11.5 <4.0.0'

dependencies:
  basic_utils: any
  collection: any
  crypto: any
  # encrypt: any
  encrypter_plus: any
  enough_convert: any
  intl: any
  json_annotation: any
  pointycastle: any
  synchronized: any
  xml: any

dependency_overrides:
  # http: ^1.4.0 # for dart_code_metrics

dev_dependencies:
  build_runner: any
  # dart_code_metrics: any
  dart_code_linter: any
  flutter_lints: any
  json_serializable: any
  lints: any
  test: any
  timezone: any
